apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: merchant-portal-client
  description: |
    Publisher Portal's Client (FE).
  links:
    - title: Publisher Portal Prod
      url: https://portal.cod.com/
    - title: Publisher Portal Staging
      url: https://publisher-portal.cod-staging.com/
    - title: Documentation
      url: https://cod.atlassian.net/wiki/spaces/ME/overview?homepageId=243892350
    - title: Bitbucket
      url: https://bitbucket.org/cod/merchant-portal-client/src/master/
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
spec:
  type: Component
  owner: Adas
  lifecycle: experimental
  system: publisher-portal
  providesApis:
    - example-grpc-api
  consumesApi:
    - login
    - settlement
    - profile
    - dashboard
    - transaction
    - finance
    - payment-methods
    - faq

